name = "worker"
compatibility_date = "2025-08-14"
main = "src/index.js"

[triggers]
crons = ["* * * * *"]

[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
